{% set name = "music21" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75512fd21c38acc7ce59eae5efb9d69c7d8d1e710d1507f9945285e443d5d505

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - chardet
    - joblib
    - jsonpickle
    - matplotlib-base
    - more-itertools
    - numpy
    - webcolors >=1.5

test:
  imports:
    - music21
  commands:
    - python -m music21.stream.tests

about:
  home: https://github.com/cuthbertLab/music21
  license: BSD-3-Clause OR LGPL-3.0-or-later
  license_family: BSD
  license_file: music21/license.txt
  summary: A Toolkit for Computer-Aided Musical Analysis.
  description: |
    A Toolkit for Computer-Aided Musical Analysis.
    Developed by cuthbertLab, Michael Scott Cuthbert (Associate Professor, MIT), Principal Investigator.
    The development of music21 is supported by the generosity of the Seaver Institute and the NEH.
  doc_url: https://web.mit.edu/music21/doc/index.html
  dev_url: https://github.com/cuthbertLab/music21

extra:
  recipe-maintainers:
    - jacobtylerwalls
