{% set name = "music21" %}
{% set version = "9.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cf4c67da2062ec164037280580d51ed06b58e84f78afc8d00f088c2bff74f4a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - chardet
    - joblib
    - jsonpickle
    - matplotlib-base
    - more-itertools
    - numpy <2.0.0
    - requests
    - webcolors >=1.5

test:
  imports:
    - music21
  commands:
    - python -m music21.stream.tests

about:
  home: https://github.com/cuthbertLab/music21
  license: BSD-3-Clause OR LGPL-3.0-or-later
  license_family: BSD
  license_file: music21/license.txt
  summary: A Toolkit for Computer-Aided Musical Analysis.
  description: |
    People use music21 to answer questions from musicology using computers,
    to study large datasets of music, to generate musical examples, to teach
    fundamentals of music theory, to edit musical notation, study music and
    the brain, and to compose music (both algorithmically and directly).
  doc_url: https://www.music21.org/music21docs/
  dev_url: https://github.com/cuthbertLab/music21

extra:
  recipe-maintainers:
    - jacobtylerwalls
