{% set python_min = "3.10" %}
{% set name = "music21" %}
{% set version = "9.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f888a84f7abfa6e727b7028cdbf7b7bd9fa746009b766ca604fb749a67078d1a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - chardet
    - joblib
    - jsonpickle
    - matplotlib-base
    - more-itertools
    - numpy <2.0.0
    - requests
    - webcolors >=1.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - music21
  commands:
    - python -m music21.stream.tests

about:
  home: https://github.com/cuthbertLab/music21
  license: BSD-3-Clause OR LGPL-3.0-or-later
  license_family: BSD
  license_file: music21/license.txt
  summary: A Toolkit for Computer-Aided Musical Analysis.
  description: |
    People use music21 to answer questions from musicology using computers,
    to study large datasets of music, to generate musical examples, to teach
    fundamentals of music theory, to edit musical notation, study music and
    the brain, and to compose music (both algorithmically and directly).
  doc_url: https://www.music21.org/music21docs/
  dev_url: https://github.com/cuthbertLab/music21

extra:
  recipe-maintainers:
    - jacobtylerwalls
